# Default values for iap-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gojektech/iap-auth
  tag: 0.1.0-b0315badc437a781036548b444b5a647280e717c
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
iapHost: "https://some"
secretName: "some-name"
clientId: "some-client"
port: 8081
refreshTimeSeconds: 3590
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
