# Default values for iap-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gojektech/iap-auth
  tag: 0.1.0-13471bc9e9513e8de770e65bcd92e1d752664f46
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
iapHost: "https://some"
secretName: "some-name"
clientId: "some-client"
port: 8081
refreshTimeSeconds: "3590s"
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
