apiVersion: v1
data:
  application.yml: |
{{ .Values.envoy | toYaml | indent 4 }}
kind: ConfigMap
metadata:
  name: {{ include "envoy-lb-operator.name" . }}-config
  namespace: {{ .Release.Namespace }}