apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-lb-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "envoy-lb-operator.name" . }}
    helm.sh/chart: {{ include "envoy-lb-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 18000
      targetPort: 18000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "envoy-lb-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
