---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.fullname" . }}
  labels:
    release: {{.Release.Name | quote }}
type: Opaque
data:
  password: {{ template "application.password" . }}
  replpassword: {{ template "replication.password" . }}
