apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "sentinel.fullname" . }}
  labels:
    release: {{.Release.Name | quote }}
spec:
  replicas: {{.Values.stolon.sentinel.replicas}}
  selector:
    matchLabels:
      name: {{ template "sentinel.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "sentinel.fullname" . }}
        release: {{.Release.Name | quote }}
        stolon-cluster: {{ template "cluster.fullname" . }}
        stolon-sentinel: "true"
    spec:
      initContainers:
        - name: wait-for-store
          image: jwilder/dockerize
          command: ['dockerize', '-timeout', '120s', '-wait', '{{ template "store.endpoint" . }}/health']
      containers:
      - name: {{ template "sentinel.fullname" . }}
        image: '{{- .Values.stolon.image.name -}}:{{- .Values.stolon.image.tag -}}'
        command:
          - "/bin/bash"
          - "-ec"
          - |
            exec gosu stolon stolon-sentinel
        env:
          - name: STSENTINEL_CLUSTER_NAME
            value: {{ template "cluster.fullname" . }}
          - name: STSENTINEL_STORE_BACKEND
            value: "etcd"
          - name: STSENTINEL_STORE_ENDPOINTS
            value: {{ template "store.endpoint" . }}
          - name: STSENTINEL_DEBUG
            value: "{{- .Values.stolon.sentinel.debug -}}"
