apiVersion: v1
kind: Service
metadata:
  name: '{{ template "proxy.service" . }}'
  labels:
    release: {{.Release.Name | quote }}
  annotations:
    {{- if .Values.stolon.proxy.expose }}
    cloud.google.com/load-balancer-type: Internal
    {{- end }}
spec:
  selector:
    stolon-proxy: "true"
    stolon-cluster: {{ template "cluster.fullname" . }}
  ports:
    - port: 5432
  {{- if .Values.stolon.proxy.expose }}
  type: LoadBalancer
  {{- end }}
