apiVersion: v1
description: Helm chart for creating PostgreSQL cluster using stolon
home: https://source.golabs.io/leap/helm-charts
name: stolon
version: 0.4.0
icon: https://github.com/sorintlab/stolon/blob/master/logos/stolon-color.png
appVersion: 0.7.0
engine: gotpl
keywords:
  - postgres
  - PostgreSQL
  - cluster
  - stolon
